//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitSelect
    {
        public long id { get; set; }
        public int studentId { get; set; }
        public int courseId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual student student { get; set; }
    }
}
